name: Detect & tag release

on:
  # on push to `main` but only if the version file changed
  push:
    branches: [ main ]
    # TODO: seems like the changed file filter never matches for some reason
    # ...maybe because merging a PR containing the change doesn't count as a push?
    paths:
      - 'app/src/main/resources/version.properties'
  # dispatching manually does work though
  workflow_dispatch:

jobs:
  tag-release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v2
        with:
          # fix for https://github.community/t/push-from-action-does-not-trigger-subsequent-action/16854/2
          persist-credentials: false
      - id: version
        run: echo "::set-output name=version::$(grep semver= app/src/main/resources/version.properties | sed 's/.*semver=\(.*\)/\1/')"

      - name: Push version git tag
        uses: julb/action-manage-tag@v1
        with:
          name: v${{ steps.version.outputs.version }}
          state: present
        env:
          # use a PAT here rather than default `GITHUB_TOKEN` so that Actions are triggered after push
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
