name: Detect & tag release

# on push to `main` but only if the version file changed
on:
  push:
    branches: [ $default-branch ]
    paths:
      - 'app/src/main/resources/version.properties'

jobs:
  tag-release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v2
      - id: version
        run: echo "::set-output name=version::$(grep semver= app/src/main/resources/version.properties | sed 's/.*semver=\(.*\)/\1/')"

      - name: Push version git tag
        uses: julb/action-manage-tag@v1
        with:
          name: v${{ steps.version.outputs.version }}
          state: present
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
