name: Homebrew build & release

# releases are created by build-release workflow
on:
  release:
    types:
      - published
  workflow_dispatch:
    # inputs:
    #   version:
    #     description: Enter latest release version (tag) to re-trigger for
    #     required: true

jobs:
  update-tap-formula:
    name: Update formula version in Homebrew tap
    runs-on: ubuntu-latest
    steps:
      # anentropic/update-homebrew-formula-action will pick up the last release from git tags
      # TODO: update the formula action to take an input
      - name: Update the Homebrew formula with latest release
        uses: anentropic/update-homebrew-formula-action@fixes-for-linter
        with:
          repository: anentropic/chuckd
          tap: anentropic/homebrew-tap
          formula: chuckd.rb
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
