name: Homebrew build & release

# releases are created by build-release workflow
on:
  release:
    types:
      - published

jobs:
  update-tap-formula:
    name: Update formula version in Homebrew tap
    runs-on: ubuntu-latest
    steps:
      - name: Update the Homebrew formula with latest release
        uses: anentropic/update-homebrew-formula-action@fixes-for-linter
        with:
          repository: anentropic/chuckd
          tap: anentropic/homebrew-tap
          formula: chuckd.rb
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

  build-and-upload-bottle:
    name: Build and upload Homebrew bottle for macOS Catalina
    strategy:
      matrix:
        os: [macos-10.15, macos-11, macos-12]
        include:
          - os: macos-10.15
            version-name: Catalina
          - os: macos-11
            version-name: Big Sur
          - os: macos-12
            version-name: Monterrey
          - os: macos-13
            version-name: Ventura
    runs-on: ${{ matrix.os }}
    needs: update-tap-formula
    outputs:
      macos-version: ${{ matrix.version-name }}
    steps:
      # yes, it's a bit redundant to the build-native-image job
      # but a homebrew bottle install should be more convenient
      # if it bypasses the Gatekeeper warnings you get otherwise
      - uses: ayltai/setup-graalvm@v1
        with:
          java-version: 11
          graalvm-version: '21.1.0'
          native-image: true

      - name: Build a bottle using Homebrew
        id: build-bottle
        env:
          # needed by anentropic/tap/chuckd so it can set PATH and JAVA_HOME
          # in the restricted env during brew install
          HOMEBREW_GRAALVM_HOME: ${{ env.GRAALVM_HOME }}
        # https://github.com/actions/virtual-environments/issues/2619
        # `sudo /usr/sbin/purge` to prevent "exec format error" after extracting
        run: |
          sudo /usr/sbin/purge
          brew install --build-bottle --verbose anentropic/tap/chuckd
          sudo /usr/sbin/purge
          brew bottle anentropic/tap/chuckd
          echo "::set-output name=bottlepath::$(find -f chuckd--${{ github.event.release.tag_name }}.catalina.bottle*)"

      - name: Upload the bottle to the GitHub release
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./${{ steps.build-bottle.outputs.bottlepath }}
          asset_name: chuckd-${{ github.event.release.tag_name }}.catalina.bottle.tar.gz
          asset_content_type: application/gzip

  update-formula-tap-bottle:
    name: Update the Homebrew formula with bottle file
    runs-on: ubuntu-latest
    needs: build-and-upload-bottle
    steps:
      - uses: anentropic/update-homebrew-formula-action@fixes-for-linter
        with:
          repository: anentropic/chuckd
          tap: anentropic/homebrew-tap
          formula: chuckd.rb
          message: |
            Add macOS ${{ needs.build-and-upload-bottle.outputs.macos-version }} bottle to chuckd ${{ github.event.release.tag_name }}
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
