name: Homebrew build & release

# releases are created by build-release workflow
on:
  release:
    types:
      - published

jobs:
  update-tap-formula:
    name: Update formula in Homebrew tap
    runs-on: ubuntu-latest
    steps:
      - name: Update the Homebrew formula with latest release
        uses: NSHipster/update-homebrew-formula-action@main
        with:
          repository: anentropic/chuckd
          tap: anentropic/homebrew-tap
          formula: chuckd.rb
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

  build-and-upload-bottle:
    name: Build and upload Homebrew bottle for macOS Catalina
    # TODO: matrix when Big Sur runners are generally available
    runs-on: macos-10.15
    needs: update-tap-formula
    outputs:
      macos-version: Catalina
    steps:
      # yes, it's a bit redundant to the build-native-image job
      # but a homebrew bottle install should be more convenient
      # if it bypasses the Gatekeeper warnings you get otherwise
      - uses: ayltai/setup-graalvm@v1
        with:
          java-version: 11
          graalvm-version: '21.1.0'
          native-image: true
      - name: Build a bottle using Homebrew
        env:
          # needed by anentropic/tap/chuckd so it can set PATH and JAVA_HOME
          # in the restricted env during brew install
          HOMEBREW_GRAALVM_HOME: ${{ env.GRAALVM_HOME }}
        run: |
          brew install --build-bottle --verbose anentropic/tap/chuckd
          brew bottle anentropic/tap/chuckd
      - name: Upload the bottle to the GitHub release
        uses: actions/upload-release-asset@v1.0.1
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./chuckd--${{ github.event.release.tag_name }}.catalina.bottle.tar.gz
          asset_name: chuckd-${{ github.event.release.tag_name }}.catalina.bottle.tar.gz
          asset_content_type: application/gzip

  update-formula-bottle:
    name: Update the Homebrew formula again with bottle
    runs-on: ubuntu-latest
    needs: build-and-upload-bottle
    steps:
      # TODO: see https://github.com/SwiftDocOrg/swift-doc/blob/master/.github/workflows/publish.yml#L61
      # for multi version workflow once Bug Sur runners are generally available
      - uses: NSHipster/update-homebrew-formula-action@main
        with:
          repository: anentropic/chuckd
          tap: anentropic/homebrew-tap
          formula: chuckd.rb
          message: |
            Add bottle for chuckd ${{ github.event.release.tag_name }}
            on macOS ${{ needs.build-and-upload-bottle.outputs.macos-version }}
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
