# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: PR build and test

on:
  pull_request:

jobs:
  build-and-test-java:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build & test with Gradle
        run: ./gradlew build

      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          check_name: Gradle unit test results
          comment_on_pr: false
          files: app/build/test-results/**/*.xml

  build-and-test-native-image:
    runs-on: ubuntu-latest
    steps:
      - uses: ayltai/setup-graalvm@v1
        with:
          java-version: 11
          graalvm-version: '21.1.0'
          native-image: true

      - uses: actions/checkout@v2
      - name: Build GraalVM native-image
        run: ./gradlew nativeImage

      - uses: mig4/setup-bats@v1
        with:
          bats-version: 1.3.0
      - run: bats --version
      - run: mkdir bats-report

      - name: Smoke-test native image
        run: bats --report-formatter junit --output bats-report ./bin-tests/smoke.bats

      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          check_name: Native-image smoke-test results
          comment_on_pr: false
          # note: this has to be relative to work dir, absolute path not supported
          # (limitation of EnricoMi/publish-unit-test-result-action not GHA)
          files: bats-report/**/*.xml
